name: Build page

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing deps
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    - name: Post-Process
      run: |
        find . -type d -not -name "dist" -print0 | xargs -0 rm --
        mv -v ./dist/* .
